---
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: ftp-watcher
  namespace: default
  annotations:
    traffic.sidecar.istio.io/includeOutboundIPRanges: INCLUDE_OUTBOUND_IPRANGES
spec:
  image: github.com/vaikas-google/ftp/cmd/source
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: ftp-dumper
  args:
  - --server=FTP_SERVER
  - -secure=false
  - --dir=FTP_DIR_TO_WTCH
  env:
  - name: FTP_USER
    valueFrom:
      secretKeyRef:
        key: user
        name: ftp-secret
  - name: FTP_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: ftp-secret
