---
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: sftp-watcher
  namespace: default
  annotations:
    traffic.sidecar.istio.io/includeOutboundIPRanges: INCLUDE_OUTBOUND_IPRANGES
spec:
  args:
  - --server=SFTP_SERVER
  - -secure=true
  - --dir=SFTP_DIR
  - --storename=sftp-store
  env:
  - name: FTP_USER
    valueFrom:
      secretKeyRef:
        key: user
        name: sftp-secret
  - name: FTP_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: sftp-secret
  image: us.gcr.io/probable-summer-223122/source-74f3a04b1b7c9dfb4efec658c9499ab6@sha256:119587b525aed967045730b24fecea8dc66fedfb21f6027cf67e3dfe81df5a75
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: ftp-dumper
